server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/work_tracker
    username: ${{ DB_USERNAME }}
    password: ${{ DB_PASSWORD }}

  jpa:
    show-sql: true
    generate-ddl: true