server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_manager
    username: postgres
    password: Password00

  jpa:
    show-sql: true
    generate-ddl: true

